name: robustqa 
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.12.8=h06a4308_0
  - certifi=2020.12.5=py36h06a4308_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.10.4=h5ab3b9f_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.2=heb0550a_3
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.2.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py36hff7bd54_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openssl=1.1.1i=h27cfd23_0
  - pillow=8.0.1=py36he98fc37_0
  - pip=20.3.1=py36h06a4308_0
  - python=3.6.8=h0371630_0
  - pytorch=1.7.1=py3.6_cuda10.1.243_cudnn7.6.3_0
  - readline=7.0=h7b6447c_5
  - setuptools=51.0.0=py36h06a4308_2
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.8.2=py36_cu101
  - typing_extensions=3.7.4.3=py_0
  - wheel=0.36.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.11.0
    - cachetools==4.2.1
    - chardet==3.0.4
    - click==7.1.2
    - dataclasses==0.8
    - datasets==1.1.3
    - dill==0.3.3
    - faiss-gpu==1.6.5
    - filelock==3.0.12
    - google-auth==1.25.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.35.0
    - idna==2.10
    - importlib-metadata==3.4.0
    - joblib==0.17.0
    - markdown==3.3.3
    - multiprocess==0.70.11.1
    - numpy==1.19.4
    - oauthlib==3.1.0
    - packaging==20.8
    - pandas==1.1.5
    - protobuf==3.14.0
    - pyarrow==2.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.4
    - regex==2020.11.13
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - sacremoses==0.0.43
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.1
    - tokenizers==0.9.4
    - torch==1.7.1
    - tqdm==4.49.0
    - transformers==4.2.2
    - urllib3==1.26.2
    - werkzeug==1.0.1
    - xxhash==2.0.0
    - zipp==3.4.0
prefix: /u/nlp/anaconda/main/anaconda3/envs/knowledge-transfer

